### ISSUE TITLE
Add routes table

### ISSUE THREAD

**Issue by iznogod** [opencj-dev/server-gsc#198] opened 2022-09-12 15:42 UTC
checkpointID unique
mapid (?) is already in checkpoints
route name
isBonus 1/0

**Comment by iznogod** [comment] 2022-09-12 15:46
type as enum (normal/bonus/secret/freeroam)
route color here too

**Comment by iznogod** [comment] 2022-09-12 15:47
difficulty

**Comment by iznogod** [comment] 2022-09-15 11:07
Added to db, needs gsc update

**Comment by Yocairo** [comment] 2023-08-03 20:45
@iznogod can you update description? I don't know what needs to be done

**Comment by iznogod** [comment] 2023-08-03 21:38
i'd have to look into it again too. Is required for alpha though.

**Comment by Yocairo** [comment] 2023-08-08 23:42
Duplicate of #174

**Closed by Yocairo** 2023-08-08 23:42 UTC
