### ISSUE TITLE
Best records (leaderboard) menu

### ISSUE THREAD

**Issue by opencj-dev** [opencj-dev/server-gsc#4] opened 2022-08-09 21:49 UTC

**Comment by Yocairo** [comment] 2022-08-23 21:32
Gonna need a sketchup from Funk for this one...

**Comment by iznogod** [comment] 2022-08-24 05:18
Both for the in-menu and in-quickmessage ones.

**Comment by Yocairo** [comment] 2022-08-24 16:33
Why should there be two leaderboard menus?

**Comment by iznogod** [comment] 2022-08-24 17:18
The in-menu one would have mouse interaction enabled, the quickmessage one just provides a few (pre-selected) records at a glance during a run.

**Comment by Yocairo** [comment] 2022-08-24 17:21
@funk what do you think, would there be any value to that in CoD4? I feel like it's kind of unnecessary to have 2 menus personally.

**Comment by fnkcj** [comment] 2022-08-25 10:50
Agree with @Yocairo.

Two menus are not necessary imo.

**Comment by Yocairo** [comment] 2023-08-03 21:27
Duplicate of #212

**Closed by Yocairo** 2023-08-03 21:27 UTC
Labels: duplicate
