### ISSUE TITLE
Runs menu + allow restoring of runs

### ISSUE THREAD

**Issue by opencj-dev** [opencj-dev/server-gsc#119] opened 2022-08-14 11:45 UTC

**Comment by iznogod** [comment] 2022-08-14 14:27
Needs menu

Also need to decide on penalty for loading old runs, like add 30 seconds and every 30 seconds update timePlayed in database?

**Comment by Yocairo** [comment] 2022-08-23 21:15
I would say no penalty, and updating timePlayed should be done the moment a player leaves, the map changes, or the run finishes IMO. I don't want the possibility of them reconnecting and trying the jump within 30 seconds - repeat 1000 times.

**Comment by iznogod** [comment] 2022-08-24 05:16
No, add 30 sec to the run when loaded using history save, then every 30 sec of player being in the run update time in db.

Otherwise ppl can just reconnect with a second account and no-penalty retry multiple times.

**Comment by Yocairo** [comment] 2022-08-24 16:31
Again, I would say no penalty. It's not necessary and it's demotivating if you have to leave abruptly.
Just don't allow login from a player that is already logged in or something.
On top of saving the time every 30 seconds, we should do so on run finished / disconnect

**Comment by iznogod** [comment] 2022-08-24 17:17
As per our previous discussion on it, it's not feasible to do that. Players crash and stay on the server at 999 ping, and disallowing them to reconnect and re-log is just annoying.

**Comment by Yocairo** [comment] 2022-08-24 17:20
If they crash/lag out, they will already have 5 seconds added to their time due to AFK timer not triggering right away. I'm not saying disallow them to reconnect, but if they connect, then kick their old client.

**Comment by iznogod** [comment] 2022-08-24 18:43
Cant check that properly and cheaply across multiple servers though, would require servers polling the db like crazy

**Comment by Yocairo** [comment] 2022-08-24 18:45
Not necessarily. Can also do that completely C sided without database.

**Comment by Yocairo** [comment] 2023-08-05 23:39
Duplicate of #183 even though this one was here earlier :-P

**Closed by Yocairo** 2023-08-05 23:39 UTC
