### ISSUE TITLE
Have the playback of ambient tracks be togglable by the player

### ISSUE THREAD

**Issue by fnkcj** [opencj-dev/server-gsc#206] opened 2022-10-16 13:53 UTC
This is a minor thing I noticed while playing around with ambient music for a new map. It seems that both JH and 3xP' force ambient music off (I'm guessing with [AmbientStop](https://wiki.zeroy.com/index.php?title=Call_of_Duty_4:_Scripting_Reference_-_Sound::AmbientStop)). Would it be possible to prevent this behavior by default and let players be able to disable the music for themselves if they want to do so? 

We could have commands like:
`!ambient // opposite of current state`
`!ambient on`
`!ambient off`

**Comment by iznogod** [comment] 2022-10-16 15:53
Closed. Duplicate of https://github.com/opencj-dev/server-gsc/issues/2

**Closed by iznogod** 2022-10-16 15:53 UTC
